included:
  - Sidequest3

excluded:
  - Sidequest3Tests
  - Sidequest3UITests

disabled_rules:
  - trailing_whitespace
  - line_length
  - type_body_length
  - file_length
  - function_body_length
  - identifier_name
  - nesting

opt_in_rules:
  - force_unwrapping
